FROM node:21

WORKDIR /${FRONT_ADMIN_POPAYAN_TOURISM_APP_NAME}/

COPY package*.json /${FRONT_ADMIN_POPAYAN_TOURISM_APP_NAME}/
RUN npm install

COPY . /${FRONT_ADMIN_POPAYAN_TOURISM_APP_NAME}/

EXPOSE ${FRONT_ADMIN_POPAYAN_TOURISM_PORT}
